### ISSUE TITLE
Spacer Regex word boundary

### ISSUE THREAD

**Issue by emerham** [itmaybejj/linkpurpose#5]
In the update that added the regex match to find the last word in the link string is incorrectly matching a string that only has one word and thus causes a extra blank space to be inserted where one shouldn't be.
![Screenshot from 2024-06-07 15-58-29](https://github.com/itmaybejj/linkpurpose/assets/9220641/daf86419-2e50-46f2-8a62-7447f9f2b716)

Propose changing the regex pattern to:
`const lastWordRegex = /\s\S+\b(?=\s*$)/g`

- \s matches any whitespace character. This could be a space, tab, form-feed, and so on.
- \S+ matches any non-whitespace character. The plus (+) means one or more, so this will match one or more non-whitespace characters.
- \b is a word boundary. This means it matches the position where a word character is not followed or preceded by another word-character.
- (?=\s*$) is a lookahead assertion. This means the regex engine will temporarily move ahead to check if the assertion can be satisfied, and if it can, it will move back to where it was and continue with the actual expression. In this case, it's looking to see if the rest of the string only contains zero or more repetitions of a whitespace character followed by the end of the string.

**Comment by itmaybejj** [comment]
Oof good catch thank you.

I played with this and changing the Regex caused a different issue -- without a match, the .nobreak class does not get applied.

I [added a separate IF instead for the spacer](https://github.com/itmaybejj/linkpurpose/commit/3a137a170b84d1ddb6162b348ac8e7a4e4621680#diff-d26c3e016a77311eb74f4fdd1d20c25e8e280ddcddb4c0b1bd440f67701e0ccdR428), so that even one-word links get the no-break, just not the spacer.

**Comment by itmaybejj** [comment]
Ack; just realized this will cause a regression with inline links that wrap their preceding space...one moment...

**Comment by itmaybejj** [comment]
ok. See if [1.0.4](https://github.com/itmaybejj/linkpurpose/releases/tag/1.0.4) works for you.
